version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: yelp-camp
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: